// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace APIVue.Models
{
    [Table("tb_produtos")]
    public partial class Produtos
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Descricao { get; set; }
        public float Preco { get; set; }
        public int QtdEstoque { get; set; }
        public string NomeArquivo { get; set; }

        [NotMapped]
        public IFormFile Img { get; set; }
        [NotMapped]
        public byte[] ImgByte { get; set; }
    }
}